name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12' # Updated to latest stable version

      - name: Build Flutter Web App
        run: |
          cd app
          flutter pub get
          flutter build web --release

          # Verify if the build/web directory exists after the build
          if [ ! -d "build/web" ]; then
            echo "Error: build/web directory does not exist"
            exit 1
          fi
          echo "Flutter Web build completed successfully, build/web directory exists."

      - name: Upload build/web as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: app/build/web

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image for government-assistant-api
        run: |
          docker build -t us-central1-docker.pkg.dev/government-assistant-001/government-assistant-docker-repo/government-assistant-api -f Dockerfile .

      - name: Push Docker images
        run: |
          docker push us-central1-docker.pkg.dev/government-assistant-001/government-assistant-docker-repo/government-assistant-api

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push
    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/183025368636/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider' 
          service_account: 'ci-cd-service-account@government-assistant-001.iam.gserviceaccount.com'

      - name: Download flutter-web-build artifact
        uses: actions/download-artifact@v3
        with:
          name: flutter-web-build
          path: flutter-web-build # Specify download path

      - name: List downloaded files
        run: |
          ls -R flutter-web-build 

      - name: Deploy Flutter Web App to Google Cloud Storage
        run: |
          gsutil -m rsync -R flutter-web-build/ gs://web-flutter-gov-bucket/

      - name: Deploy to Cloud Run (government-assistant-api)
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        run: |
          gcloud run deploy government-assistant-api \
            --image us-central1-docker.pkg.dev/government-assistant-001/government-assistant-docker-repo/government-assistant-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --update-env-vars XAI_API_KEY=$XAI_API_KEY